name: DEPLOYMENT

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: setup RSA private key
        id: setup-rsa-private-key
        run: |
          echo "-----BEGIN RSA PRIVATE KEY-----" >> EC2KeyPair.pem
          echo "${SSH_PRIVATE_KEY}" >> EC2KeyPair.pem
          echo "-----END RSA PRIVATE KEY-----" >> EC2KeyPair.pem
          sudo cat EC2KeyPair.pem
          chmod 600 EC2KeyPair.pem
          ssh -i EC2KeyPair.pem ubuntu@ec2-3-95-200-25.compute-1.amazonaws.com ./deploy.sh 
