name: DEPLOYMENT

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
  AWS_EC2_IP: ${{ secrets.AWS_EC2_IP }}
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: setup RSA private key
        id: setup-rsa-private-key
        run: |
          echo "${SSH_PRIVATE_KEY}" >> EC2KeyPair.pem
          chmod 600 EC2KeyPair.pem

      - name: Deploy application
        id: deploy-application
        run: ssh -i EC2KeyPair.pem -o StrictHostKeyChecking=no ${{env.AWS_USERNAME}}@${{ env.AWS_EC2_IP }} ./deploy.sh 
